### ISSUE TITLE
Zoom attribute seems to be ignored

### ISSUE THREAD

**Issue by xavier-heysch** [brh55/react-native-open-maps#12]
Hi everyone

I have just installed react-native-open-maps v0.2.2 and it does the job well! But I have a small issue.

I have tried to define the zoom using openMap or createOpenLink methods, but it seems to be ignored all the time.

I'm seeing this issue on a iPhone 5S (iOS 11) with Plans app and GoogleMap in webview (when forcing provider to "google").

Is there anyone who got this issue too ?

**Comment by brh55** [comment]
@xavier-heysch 
Good catch, in order to add support for some marker with Google, we needed to use a "query" action, which doesn't support zoom. 

I've changed the behavior with the latest updates (v0.3.1), you can use the combination of `latitude` and `longitude` + `zoom` to open the maps (Google maps won't support a marker) with zoom being respected.
