### ISSUE TITLE
Possibility to open map with sdress

### ISSUE THREAD

**Issue by robsonrobi** [brh55/react-native-open-maps#5]
Is it possible to set a destination adress instead of latitude and longitude? That would be awesome.

**Comment by brh55** [comment]
Hmm that would be a neat concept, if there is enough interest, I would consider embedding this, since it's not hard to do at all with Google geocoding!

**Comment by assafb81** [comment]
@robsonrobi, @brh55:
My code to open google maps or apple maps with a string address is (I did some change in @brh55  code):

```
const createMapLink = (addressStr, mapProvider) => {
    if (mapProvider === 'apple') {
        return `http://maps.apple.com/?q=${addressStr}`;
    }
    return `https://www.google.com/maps/search/?api=1&query=${addressStr}`;
};

const openNavigationApp = (addressStr) => {
    const mapProvider = (Platform.OS === 'ios') ? 'apple' : 'google';
    const mapLink = createMapLink(data, mapProvider);

    Linking.openURL(mapLink)
        .catch(err => console.error('An error occurred', err));
};
```

An example for a address string:
`FL, Miami, 3565 NW 245th Street Rd`

hope it helps

**Comment by brh55** [comment]
Since the `pin` option has been implemented, this can be achieved by removing the `ll` param in apple maps and google maps *(I assume here for GMaps)*.

**Comment by TimurAsayonok** [comment]
@brh55 Any news?

**Comment by brh55** [comment]
@TimurAsayonok  with v0.2.0 you should be able to use the `query` property to specify the address, not supported on Apple Maps. But someone is more than welcomed to PR this, would probably just be a couple of `ifs`.

**Comment by TimurAsayonok** [comment]
@brh55 thanks for reply, will check how it's works

**Comment by Beissner** [comment]
@brh55 the `query` property isn't working on Apple Maps. Has anyone found a solution?

**Comment by TimurAsayonok** [comment]
@Beissner I found problem for IOS. 
@brh55 in method `open()` in index.js we don't have `query`. We have jus `open({ latitude, longitude, zoomLevel, name, provider})`. If you want to use `open()` with `query` this method should be like - `open({ latitude, longitude, zoomLevel, name, provider, query})`. 

Another, in method `open()` in the input parameters we have prop `name` but we don't use this prop into `createOpenLink()` a and `createMapLink()`.

@brh55 let me know what do you think.

**Comment by brh55** [comment]
@TimurAsayonok 
You're right, I rushed and missed the update to `open()`, let's submit a PR to replace the name parameter with `query`. This should fix issue with Apple Maps and Google Maps if you are using the `Open` functionality.

We should be using `https://www.google.com/maps/search/?api=1` as it's a [cross-platform url](https://developers.google.com/maps/documentation/urls/guide).

The issue is it only accepts the `q` parameter, but it accepts `lat` and `long`, `address`, or a `place name`. So it doesn't support both a `ll` and `q`, but this is by design, and a marker should still be present regardless of input.

I would suggest external validation would be more appropriate if you are inserting a wrong query?

**Comment by brh55** [comment]
If anyone is up to fixing this, taking PR to just fix the `open()` function. Simple fix, just need to simply remove `name` and use `query` instead.

**Comment by TimurAsayonok** [comment]
@brh55 today i will crate PR

**Comment by tspiva** [comment]
There seems to be an issue with google maps displaying the pin.  According to the docs linked above, the parameter should be called "query" instead of "q" unless I'm missing something.

I changed the `createMapLink` to this to get the pin working on google maps (and easily get directions):

```
	if (query) {
		link.google = link.google.concat(`&query=${query}`);
		link.apple = link.apple.concat(`&q=${query}`);
	} else {
		link.google = link.google.concat(`&query=${latitude},${longitude}`)
	}
```
Note: I'm not sure about apple as I'm just working in android at the moment.

Is this the desired behavior?

**Comment by brh55** [comment]
@tspiva Ops, you're right, apple maps should be remain as `q` and google maps should be `query` this will allow pin + address. Can you please send a PR for fix?

**Comment by tspiva** [comment]
PR done
